#include "EstadoJuego.h"

LiquidCrystal_I2C lcd(DIRECCION_LCD, COLUMNAS_LCD, FILAS_LCD);
Pantalla pantallaActual = PANTALLA_INICIO;
uint8_t opcionMenu = 0;
uint8_t jugadorX = COLUMNA_MIN;
uint8_t jugadorY = 2;
uint16_t puntaje = 0;
uint8_t vidas = VIDAS_INICIALES;
uint8_t nivel = NIVEL_INICIAL;
unsigned long ultimoDanioMs = 0;
const unsigned long tiempoInvulnerableDanioMs = 700;
bool modoAdmin = false;
bool juegoPausado = false;
char comandoSerial[TAMANIO_BUFFER_COMANDO];
uint8_t indiceComando = 0;
Marcador marcadores[TOTAL_MARCADORES];
const int EEPROM_DIRECCION_FIRMA = 0;
const int EEPROM_DIRECCION_DATOS = 4;
const byte EEPROM_FIRMA = 0x42;
char nombreNuevo[LETRAS_NOMBRE + 1] = {'A', 'A', 'A', '\0'};
uint8_t indiceNombre = 0;
int8_t posicionNuevoMarcador = -1;
bool balaActiva[TOTAL_BALAS] = {false, false, false};
int8_t balaX[TOTAL_BALAS] = {0, 0, 0};
uint8_t balaY[TOTAL_BALAS] = {1, 2, 3};
unsigned long ultimoMovimientoBalaMs[TOTAL_BALAS] = {0, 0, 0};
const unsigned long velocidadBalaMs = 150;
bool enemigoActivo[MAXIMO_ENEMIGOS];
int8_t enemigoX[MAXIMO_ENEMIGOS];
uint8_t enemigoY[MAXIMO_ENEMIGOS];
uint8_t enemigoTipo[MAXIMO_ENEMIGOS];
unsigned long ultimoMovimientoEnemigoMs = 0;
unsigned long ultimaOleadaMs = 0;
unsigned long velocidadEnemigoMs = 650;
unsigned long intervaloOleadaMs = 2200;
uint8_t maximoEnemigosActivos = 4;
int8_t aparicionXMin = COLUMNA_MAX;
int8_t aparicionXMax = COLUMNA_MAX;
uint8_t indicePatronMaximo = 3;
bool proyectilEspecialActivo = false;
int8_t especialX = 0;
uint8_t especialY = 0;
unsigned long ultimoMovimientoEspecialMs = 0;
const unsigned long velocidadEspecialMs = 120;
bool explosionActiva = false;
int8_t explosionX = 0;
uint8_t explosionY = 0;
bool mascaraExplosion[FILAS_JUEGO][FILAS_JUEGO];
unsigned long inicioExplosionMs = 0;
const unsigned long duracionExplosionMs = 450;
unsigned long ultimoEspecialMs = 0;
const unsigned long recargaEspecialMs = 8000;
bool especialUsadoUnaVez = false;
bool ultimoArriba = HIGH;
bool ultimoAbajo = HIGH;
bool ultimoDerecha = HIGH;
bool ultimoIzquierda = HIGH;
bool ultimoDisparo1 = HIGH;
bool ultimoDisparo2 = HIGH;
unsigned long ultimoCambioBotonMs[TOTAL_INDICES_BOTON];
const unsigned long tiempoReboteMs = 25;
unsigned long ultimaActualizacionBarraMs = 0;
bool areaJuegoPendiente = false;
uint8_t cacheJuego[FILAS_JUEGO][COLUMNAS_LCD];
bool musicaActiva = true;
uint8_t indiceMusica = 0;
bool notaMusicaIniciada = false;
unsigned long inicioNotaMusicaMs = 0;
const uint16_t *frecuenciasEfecto = NULL;
const uint16_t *duracionesEfecto = NULL;
uint8_t longitudEfecto = 0;
uint8_t indiceEfecto = 0;
bool efectoActivo = false;
unsigned long inicioNotaEfectoMs = 0;
